# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mijs Bjorn
title: ICT Expert & Trainer
email: bjorn.mijs@student.pxl.be
website: https://www.linkedin.com/in/bjorn-mijs-5463a996/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  MijsBjornPXL
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: bjorn-mijs-5463a996
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: BjornMijs
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Met meer dan 15 jaar ervaring in de ICT-sector heb ik mijn carrière gewijd aan het beheren en optimaliseren van netwerken voor bedrijven, het oplossen van complexe ICT-uitdagingen, en het delen van mijn kennis via training en coaching. Mijn expertise strekt zich uit over netwerkbeheer, troubleshooting van complexe infrastructuren, en het ontwikkelen van efficiënte oplossingen op maat voor diverse klantbehoeften.

  I am most skilled in: <mark>Networking</mark> and <mark>tasting wine</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: Proximus
        link: proximus.be
        # link_text: boringcompany.com
        sub_title: Technical Expert & Trainer
        caption: Feb 2018 - Jun 2024
        description: | # this will include new lines to allow paragraphs
          I managed customer networks, designed technical solutions, and resolved complex ICT issues. My focus was on developing and delivering training materials, supporting over 300 users, and implementing technologies such as VMware, Cisco, and Windows Server. Additionally, I wrote scripts and created interactive learning tools to enhance technical knowledge.
        quote: >
          "Combining technical expertise with effective training to manage networks, resolve complex ICT challenges, and foster the development of internal and external teams."
      - layout: right
        title: Proximus
        link: proximus.be
        # link_text: boringcompany.com
        sub_title: Team Coach - PRF Market
        caption: Sep 2017 - Feb 2018
        description: | # this will include new lines to allow paragraphs
          As a Team Coach for the PRF Market, I focused on teaching key skills and techniques to improve team performance. I monitored progress, identified strengths and weaknesses, and provided strategic advice on IT and VoIP issues. Additionally, I developed targeted training programs to enhance team effectiveness.
        quote: >
          "Empowering teams by teaching essential skills, enhancing performance, and providing strategic guidance to drive success in the PRF market."

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Remote Platform PABX
        # caption: 
        sub_title: Associated with Proximus
        quote: >
          "Employees used an old VPN-connection for managing the install base for old PBX-devices. My company needed additional PC's/Laptops for making this connection. VPN was connected by a public ip address, this isn't allowed on our professional intranet connection. My goal was finding a solution so our company didn't need extra PC's/notebooks for managing these devices.""
        description: | # this will include new lines to allow paragraphs
          Update old PBX-mgmnt program to a new more efficient method.
      - layout: left
        title: Mivo430 SMBC
        # caption: 
        sub_title: Associated with Proximus
        quote: >
          "Introduce & train technicians/remote helpdesk employees for the upcoming Mivo400 pbx"
        description: | # this will include new lines to allow paragraphs
          Develop guidelines, Testing CPE & Follow up first installs

  - title: Skills  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: Hard skills
        #sub_title: Electronica ICT
        description: |

          - Network Management: Expertise in managing networks, including LAN, WAN, SD-WAN, and VoIP.

          - Server Management: Proficient in maintaining Windows Server environments (DHCP, RDP, IP-Virtualization, AD).

          - Cloud Networking (GCP, AWS, etc.): Experience with cloud network infrastructures.

          - Training Development: Experience in developing and presenting training programs, webinars, and workshops.

          - E-learning Creation: Expertise in creating interactive e-learnings using tools (Flowsparks, Adobe Photoshop...)

          - Troubleshooting and Problem Solving: Ability to resolve complex ICT issues, including system optimization and debugging for both field and remote technicians.
          
          - CPE Configuration: Experience in configuring and troubleshooting CPE devices (Cisco, Huawei, OneAccess, Technicolor, PBX systems).
                              
          - Virtualization: Experience with VMware, Hypervisor, vSphere, and KVM for creating and managing virtual environments.
                              
          - Scripting & Automation: Knowledge of writing scripts in Visual Basic, VBScript, Bash, and Python for system automation and problem-solving.
          
          -

          ------------------------------------------------------------------
      - layout: left
        title: Soft skills
        #sub_title: Electronica ICT
        description: |  
          - Communication: Ability to clearly explain complex technical concepts to both technical and non-technical teams.

          - Collaboration: Strong collaboration skills to effectively work with cross-functional teams.          
          
          - Problem-Solving: Creative and analytical thinking to develop innovative network solutions.
          
          - Leadership: Ability to lead project teams and implement network strategies.
          
          - Adaptability: Flexible and able to quickly respond to changes and new technologies.
          
          - Innovation-Driven: Continuously striving for improvements and embracing new technologies.

  - title: Courses # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: Cisco ICND1 & ICND2
        #caption: 2006-2008
        sub_title: Associated with Proximus
      - layout: right
        title: ECMS1 (Engineering Cisco Meraki Solutions 1)
        caption: 1999 - 2006
        sub_title: Associated with Proximus

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bachelor ICT, ICT and Telecommunicatie
        caption: 2006-2008
        sub_title: Electronica ICT
        quote: >
          "Dropped out in second year.
        description: | # this will include new lines to allow paragraphs
          Flemish Catholic university of applied sciences until September 2012. KH Kempen was a member of the KU Leuven Association. In 2012, it merged with Lessius Antwerp and Lessius Mechelen to form Thomas More University of Applied Sciences.      - layout: right
      - layout: left
        title: Provil
        caption: 1999 - 2006
        sub_title: Electronica ICT
        quote: >
          "Provil is a warm school where respect, safety, and quality education are central, with a focus on a unique learning path for each student."
        description: | # this will include new lines to allow paragraphs
          Offering a wide range of general, technical, and vocational education. It focuses on respect, collaboration, and lifelong learning, with programs in STEM, sports, and technical fields. Provil also provides dual learning, combining education with practical experience in companies.  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Fitness
      - Coding
      - Movies
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
